# Generated by Django 2.2.2 on 2020-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20201019_0649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
